[build]
  publish = "build"
  command = "yarn build && yarn functions:build"
  functions = "functions/dist"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

